name: Clipboard Builds

on:
  workflow_dispatch
# on: [ push, pull_request ]

jobs:
  linux_x11wl:
    strategy:
      fail-fast: false
      matrix:
        gcc: [ 12 ]
        arch:
          #- os: i386
          #  gcc: i686-linux-gnu
          #  needs_ports: "0"

          - os: amd64
            gcc: x86_64-linux-gnu
            needs_ports: "0"

          - os: arm64
            gcc: aarch64-linux-gnu
            needs_ports: "1"

          - os: riscv64
            gcc: riscv64-linux-gnu
            needs_ports: "1"

          - os: armhf
            gcc: arm-linux-gnueabihf
            needs_ports: "1"

          - os: ppc64el
            gcc: powerpc64le-linux-gnu
            needs_ports: "1"

          #- os: s390x
          #  gcc: s390x-linux-gnu
          #  needs_ports: "1"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          GPP_PACKAGE="g++-${{ matrix.gcc }}-${{ matrix.arch.gcc }}"
          if [[ "${{ matrix.arch.gcc }}" == "$(uname --processor)-linux-gnu" ]]; then          
            GPP_PACKAGE="g++-${{ matrix.gcc }}"
          fi
          
          if [[ "${{ matrix.arch.needs_ports }}" == "1" ]]; then
            sudo echo "deb [arch=${{ matrix.arch.os }}] http://ports.ubuntu.com/ $(lsb_release -sc) main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=${{ matrix.arch.os }}] http://ports.ubuntu.com/ $(lsb_release -sc)-updates main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=${{ matrix.arch.os }}] http://ports.ubuntu.com/ $(lsb_release -sc)-security main multiverse universe" | sudo tee -a /etc/apt/sources.list
            sudo echo "deb [arch=${{ matrix.arch.os }}] http://ports.ubuntu.com/ $(lsb_release -sc)-backports main multiverse universe" | sudo tee -a /etc/apt/sources.list
          fi
          
          # This limits apt to only looking or amd64 and i386 from Azure, see https://github.com/actions/virtual-environments/issues/1961
          sudo sed -i'' -E 's/^deb http:\/\/(azure.archive|security).ubuntu.com/deb [arch=amd64,i386] http:\/\/\1.ubuntu.com/' /etc/apt/sources.list

          sudo dpkg --add-architecture "${{ matrix.arch.os }}"
          sudo apt-get update
          sudo apt-get install -y \
            "${GPP_PACKAGE}" \
            "libx11-dev:${{ matrix.arch.os }}" \
            "libwayland-dev:${{ matrix.arch.os }}" \
            "wayland-protocols:${{ matrix.arch.os }}"
          
          cd build
          
          cmake .. \
            "-DCMAKE_CXX_COMPILER=${{ matrix.arch.gcc }}-g++-${{ matrix.gcc }}" \
            "-DCMAKE_C_COMPILER=${{ matrix.arch.gcc }}-gcc-${{ matrix.gcc }}" \
            "-DCMAKE_BUILD_TYPE=MinSizeRel"
          
          cmake --build . -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-linux-${{ matrix.arch.os }}
          path: build/output
  macos-arm64-amd64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build . -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-macos-arm64-amd64
          path: build/output
  windows-amd64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build . --config Release -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-windows-amd64
          path: build/output
  windows-arm64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=ARM64
          cmake --build . --config Release -j 3
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-windows-arm64
          path: build/output
  freebsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.13.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.1'
          shell: bash
          run: |
            sudo pkg install -y cmake llvm15 xorg wayland
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_C_COMPILER=clang15 -DCMAKE_CXX_COMPILER=clang++15 -DNO_X11=1
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-freebsd-amd64
          path: build/output
  openbsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.13.0
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.2'
          shell: bash
          run: |
            sudo pkg_add cmake
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DNO_X11=1
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-openbsd-amd64
          path: build/output
  openbsd-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.13.0
        with:
          operating_system: openbsd
          architecture: arm64
          version: '7.2'
          shell: bash
          run: |
            sudo pkg_add cmake
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DNO_X11=1
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-openbsd-arm64
          path: build/output
  netbsd-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        uses: cross-platform-actions/action@v0.13.0
        with:
          operating_system: netbsd
          architecture: x86_64
          version: '9.2'
          shell: bash
          run: |
            sudo pkgin -y install cmake gcc12
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_C_COMPILER=/usr/pkg/gcc12/bin/gcc -DCMAKE_CXX_COMPILER=/usr/pkg/gcc12/bin/g++
            cmake --build . -j 2
      - uses: actions/upload-artifact@v3
        with:
          name: clipboard-netbsd-amd64
          path: build/output